# group imports into three sections, separated by new lines:
# - std lib
# - external crates
# - local crate
#
# group_imports feature doesn't work in stable yet, so adding for future,
# and organizing imports by hand for now
#
# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#group_imports
group_imports = "StdExternalCrate"
